import {useEffect,useState} from 'react';
import type {Session} from '@supabase/supabase-js';
import {LockKeyhole,ArrowRight,Mail} from 'lucide-react';
import {supabase,configured,asset} from '@/lib/supabase';
import Workspace from './workspace';
export default function App(){const [session,setSession]=useState<Session|null>(null),[loading,setLoading]=useState(true),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[mode,setMode]=useState<'login'|'signup'|'reset'|'update'>('login'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState('');
useEffect(()=>{if(!supabase){setLoading(false);return}supabase.auth.getSession().then(({data,error})=>{if(error)setError(error.message);setSession(data.session);setLoading(false)});const {data}=supabase.auth.onAuthStateChange((event,s)=>{setSession(s);if(event==='PASSWORD_RECOVERY')setMode('update')});return()=>data.subscription.unsubscribe()},[]);
async function submit(e:React.FormEvent){e.preventDefault();if(!supabase)return;setBusy(true);setError('');setNotice('');try{const redirect=location.origin+import.meta.env.BASE_URL;let result;if(mode==='signup')result=await supabase.auth.signUp({email,password,options:{emailRedirectTo:redirect}});else if(mode==='reset')result=await supabase.auth.resetPasswordForEmail(email,{redirectTo:redirect});else if(mode==='update')result=await supabase.auth.updateUser({password});else result=await supabase.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(mode==='signup')setNotice('راجع بريدك لتأكيد الحساب. الوصول لمساحة كيرا متاح للأعضاء المضافين فقط.');if(mode==='reset')setNotice('لو الحساب متاح، هيوصلك رابط استعادة كلمة المرور.');if(mode==='update'){setNotice('تم تحديث كلمة المرور.');setMode('login')}}catch(e:any){setError(e.message==='Invalid login credentials'?'البريد أو كلمة المرور غير صحيحة.':e.message)}finally{setBusy(false)}}
if(loading)return <div className="auth-page"><p>جارٍ فتح مساحة كيرا…</p></div>;
if(session&&mode!=='update')return <Workspace/>;
return <main className="auth-page"><section className="auth-card"><img src={asset('kira-logo.webp')} alt="Kira"/><span className="eyebrow">YOUR STUDIO. ONE WORKSPACE.</span><h1>{mode==='signup'?'حساب جديد':mode==='reset'?'استعادة الدخول':mode==='update'?'كلمة مرور جديدة':'أهلًا بيك في كيرا'}<span className="red">.</span></h1><p>العملاء والفريق والمستندات، في مساحة واحدة.</p>{!configured?<div className="error-banner">تجهيز قاعدة البيانات لم يكتمل بعد. يلزم ربط مشروع Supabase قبل استخدام مساحة العمل.</div>:<form onSubmit={submit}>{mode!=='update'&&<label className="field"><span>البريد الإلكتروني</span><input type="email" required autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} dir="ltr"/></label>}{mode!=='reset'&&<label className="field"><span>كلمة المرور</span><input type="password" required minLength={8} autoComplete={mode==='login'?'current-password':'new-password'} value={password} onChange={e=>setPassword(e.target.value)} dir="ltr"/></label>}{error&&<p className="form-error" role="alert">{error}</p>}{notice&&<p className="notice" role="status">{notice}</p>}<button className="primary" disabled={busy}><LockKeyhole size={17}/>{busy?'جارٍ المتابعة…':mode==='signup'?'إنشاء الحساب':mode==='reset'?'إرسال رابط الاستعادة':mode==='update'?'حفظ كلمة المرور':'تسجيل الدخول'}</button><div className="auth-links">{mode==='login'?<><button type="button" onClick={()=>{setMode('signup');setError('')}}>أول مرة؟ أنشئ حسابك</button><button type="button" onClick={()=>{setMode('reset');setError('')}}>نسيت كلمة المرور؟</button></>:<button type="button" onClick={()=>{setMode('login');setError('')}}>العودة لتسجيل الدخول</button>}</div></form>}<small>حسابات الفريق فقط · البيانات محفوظة بصلاحيات مستقلة</small></section><span className="auth-footer">KIRA STUDIO / WORKSPACE</span></main>}
