'use client';
import {useState,useEffect} from 'react';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Plus,Trash2,Save,FileCheck} from 'lucide-react';
import {day,stages,docKinds,roles,totals,money,type Row,type Member,type Kind} from '@/lib/model';
export function Pick({value,onChange,options,label}:{value:string;onChange:(s:string)=>void;options:(string|{value:string;label:string})[];label?:string}){return <Select dir="rtl" value={value||'__none'} onValueChange={v=>onChange(v==='__none'?'':v)}><SelectTrigger aria-label={label} className="pick"><SelectValue/></SelectTrigger><SelectContent>{options.map(o=>{const v=typeof o==='string'?o:o.value;return <SelectItem key={v||'__none'} value={v||'__none'}>{typeof o==='string'?o:o.label}</SelectItem>})}</SelectContent></Select>}
export function Field({label,children,wide=false}:{label:string;children:React.ReactNode;wide?:boolean}){return <label className={wide?'field wide':'field'}><span>{label}</span>{children}</label>}
export type Edit={kind:Kind|'member';row?:any;clientId?:string;data?:any};
const defaults:any={client:{name:'',contact:'',email:'',phone:'',industry:'',source:'',notes:'',status:'محتمل'},deal:{title:'',value:0,currency:'EGP',stage:'جديد',nextAction:'',due:'',lostReason:'',notes:'',closedAt:''},task:{title:'',due:day(),status:'مفتوحة',priority:'عادية',notes:'',projectId:''},project:{title:'',status:'لم يبدأ',due:'',notes:'',dealId:''},note:{title:'',channel:'ملاحظة',body:''},payment:{documentId:'',amount:0,date:day(),method:'تحويل بنكي',reference:''},service:{name:'',price:0,currency:'EGP',details:''},settings:{name:'Kira Studio',email:'',phone:'',address:'',bank:'',iban:'',taxId:'',terms:''},document:{title:'عرض سعر',docKind:'quote',currency:'EGP',items:[{name:'',qty:1,price:0,details:''}],discount:0,taxRate:0,date:day(),due:'',scope:'',terms:'',sourceId:'',dealId:'',status:'مسودة',number:''},member:{name:'',email:'',role:'sales',active:1}};
const labels:any={client:'عميل',deal:'فرصة',task:'متابعة',project:'مشروع',document:'مستند',note:'تواصل',payment:'دفعة',service:'خدمة',settings:'بيانات الاستوديو',member:'عضو فريق'};
export function Editor({edit,rows,members,me,onClose,onSave}:{edit:Edit;rows:Row[];members:Member[];me:Member;onClose:()=>void;onSave:(p:any)=>Promise<void>}){const [d,setD]=useState<any>(()=>({...defaults[edit.kind],...(edit.kind==='member'?edit.row:edit.row?.data),...edit.data}));const [clientId,setClient]=useState(edit.row?.clientId||edit.clientId||'');const [owner,setOwner]=useState(edit.row?.owner||me.email);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const k=edit.kind;const set=(key:string,v:any)=>setD((x:any)=>({...x,[key]:v}));const input=(key:string,label:string,type='text',wide=false)=><Field label={label} wide={wide}><input disabled={k==='member'&&key==='email'&&!!edit.row} type={type} value={d[key]??''} onChange={e=>set(key,type==='number'?Number(e.target.value):e.target.value)} min={type==='number'?0:undefined} step={type==='number'?'0.01':undefined}/></Field>;const area=(key:string,label:string)=><Field label={label} wide><textarea value={d[key]||''} onChange={e=>set(key,e.target.value)} rows={3}/></Field>;const select=(key:string,label:string,options:any[])=><Field label={label}><Pick label={label} value={String(d[key]??'')} onChange={v=>set(key,v)} options={options}/></Field>;
async function submit(issue=false){setBusy(true);setError('');try{await onSave(k==='member'?{action:'member',member:d}:{kind:k,id:edit.row?.id,version:edit.row?.version,owner,clientId,data:{...d,...(k==='document'?{status:issue?'صادر':'مسودة'}:{})}});onClose()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
return <Dialog open onOpenChange={v=>!v&&!busy&&onClose()}><DialogContent dir="rtl" className={k==='document'?'editor editor-large':'editor'}><DialogHeader><DialogTitle>{edit.row?'تعديل':'إضافة'} {labels[k]}</DialogTitle><DialogDescription>{k==='document'?'راجع التفاصيل. الإصدار يحفظ نسخة ثابتة من المستند وبيانات الطرفين.':'التفاصيل الصحيحة بتسهّل الخطوة القادمة.'}</DialogDescription></DialogHeader><form onSubmit={e=>{e.preventDefault();submit()}}><fieldset disabled={busy}><div className="form-grid">{!['client','service','settings','member'].includes(k)&&<Field label="العميل"><Pick label="العميل" value={clientId} onChange={setClient} options={[{value:'',label:'اختر العميل'},...rows.filter(r=>r.kind==='client').map(r=>({value:r.id,label:r.data.name}))]}/></Field>}{me.role==='admin'&&!['member','settings','payment'].includes(k)&&<Field label="المسؤول"><Pick label="المسؤول" value={owner} onChange={setOwner} options={members.filter(m=>m.active).map(m=>({value:m.email,label:m.name}))}/></Field>}
{k==='client'&&<>{input('name','اسم الشركة / العميل *')}{input('contact','جهة التواصل')}{input('email','البريد الإلكتروني','email')}{input('phone','رقم الهاتف','tel')}{input('industry','المجال')}{input('source','مصدر العميل')}{select('status','الحالة',['محتمل','نشط','مؤرشف'])}{area('notes','ملاحظات عن العميل')}</>}
{k==='deal'&&<>{input('title','اسم الفرصة *')}{input('value','القيمة المتوقعة','number')}{select('currency','العملة',['EGP','SAR','USD','AED'])}{select('stage','المرحلة',[...stages])}{input('nextAction','الخطوة القادمة')}{input('due','موعد المتابعة','date')}{d.stage==='مفقودة'&&input('lostReason','سبب الخسارة *')}{area('notes','ملخص الاحتياج')}</>}
{k==='task'&&<>{input('title','المتابعة المطلوبة *')}{input('due','الموعد','date')}{select('priority','الأولوية',['عادية','عاجلة'])}{select('status','الحالة',['مفتوحة','مكتملة'])}{select('projectId','المشروع',[{value:'',label:'بدون مشروع'},...rows.filter(r=>r.kind==='project'&&r.clientId===clientId).map(r=>({value:r.id,label:r.data.title}))])}{area('notes','التفاصيل')}</>}
{k==='project'&&<>{input('title','اسم المشروع *')}{select('status','حالة التنفيذ',['لم يبدأ','قيد التنفيذ','بانتظار العميل','مكتمل'])}{input('due','موعد التسليم','date')}{area('notes','نطاق العمل والتسليمات')}</>}
{k==='note'&&<>{select('channel','نوع التواصل',['ملاحظة','مكالمة','اجتماع','واتساب','إيميل'])}{input('title','عنوان التواصل *')}{area('body','ما الذي تم الاتفاق عليه؟')}</>}
{k==='payment'&&<>{select('documentId','الفاتورة',[{value:'',label:'اختر الفاتورة'},...rows.filter(r=>r.kind==='document'&&r.clientId===clientId&&r.data.docKind==='invoice'&&r.data.status==='صادر').map(r=>({value:r.id,label:r.data.number+' · '+money(totals(r.data).total,r.data.currency)}))])}{input('amount','المبلغ المسدد *','number')}{input('date','تاريخ السداد','date')}{select('method','وسيلة الدفع',['تحويل بنكي','نقدي','بطاقة','أخرى'])}{input('reference','مرجع العملية')}</>}
{k==='service'&&<>{input('name','اسم الخدمة *')}{input('price','السعر','number')}{select('currency','العملة',['EGP','SAR','USD','AED'])}{area('details','المخرجات ونطاق الخدمة')}</>}
{k==='settings'&&<>{input('name','الاسم على المستندات *')}{input('email','البريد الإلكتروني','email')}{input('phone','الهاتف')}{input('address','العنوان')}{input('bank','البنك')}{input('iban','رقم الحساب / IBAN')}{input('taxId','الرقم الضريبي')}{area('terms','الشروط الافتراضية للمستندات')}</>}
{k==='member'&&<>{input('name','الاسم *')}{input('email','بريد العضو *','email')}{select('role','الدور',Object.entries(roles).map(([value,label])=>({value,label})))}<Field label="حالة العضو"><Pick value={String(d.active)} onChange={v=>set('active',Number(v))} options={[{value:'1',label:'نشط'},{value:'0',label:'موقوف'}]}/></Field><p className="form-hint wide">أضف بريد العضو وحدد دوره، ثم يقدر ينشئ حسابه بنفس البريد ويؤكده. لا يتم إرسال دعوة تلقائية.</p></>}
{k==='document'&&<>{select('docKind','نوع المستند',Object.entries(docKinds).filter(([v])=>me.role!=='sales'||v!=='invoice').map(([value,label])=>({value,label})))}{input('title','عنوان المستند *')}{select('currency','العملة',['EGP','SAR','USD','AED'])}{input('date','تاريخ الإصدار','date')}{input('due',d.docKind==='quote'?'صالح حتى':'تاريخ الاستحقاق / النهاية','date')}{select('dealId','الفرصة المرتبطة',[{value:'',label:'بدون فرصة'},...rows.filter(r=>r.kind==='deal'&&r.clientId===clientId).map(r=>({value:r.id,label:r.data.title}))])}<div className="wide item-editor"><div className="line-title"><h3>الخدمات والبنود</h3><Pick value="" label="إضافة خدمة محفوظة" onChange={id=>{const s=rows.find(r=>r.id===id);if(s)set('items',[...d.items,{name:s.data.name,qty:1,price:s.data.price,details:s.data.details}])}} options={[{value:'',label:'من مكتبة الخدمات'},...rows.filter(r=>r.kind==='service'&&r.data.currency===d.currency).map(r=>({value:r.id,label:r.data.name}))]}/></div>{d.items.map((item:any,i:number)=><div className="item-fields" key={i}><Field label="الخدمة *"><input value={item.name} onChange={e=>set('items',d.items.map((x:any,j:number)=>j===i?{...x,name:e.target.value}:x))}/></Field><Field label="الكمية"><input type="number" min="0.01" step="0.01" value={item.qty} onChange={e=>set('items',d.items.map((x:any,j:number)=>j===i?{...x,qty:Number(e.target.value)}:x))}/></Field><Field label="سعر الوحدة"><input type="number" min="0" step="0.01" value={item.price} onChange={e=>set('items',d.items.map((x:any,j:number)=>j===i?{...x,price:Number(e.target.value)}:x))}/></Field><button type="button" className="icon-button" aria-label="حذف البند" disabled={d.items.length===1} onClick={()=>set('items',d.items.filter((_:any,j:number)=>j!==i))}><Trash2 size={16}/></button><Field label="نطاق الخدمة" wide><textarea rows={2} value={item.details} onChange={e=>set('items',d.items.map((x:any,j:number)=>j===i?{...x,details:e.target.value}:x))}/></Field></div>)}<button type="button" className="text-button" onClick={()=>set('items',[...d.items,{name:'',qty:1,price:0,details:''}])}><Plus size={16}/> إضافة بند</button></div>{input('discount','الخصم (مبلغ)','number')}{input('taxRate','الضريبة %','number')}{area('scope',d.docKind==='proposal'?'فهم الاحتياج والمنهج والجدول الزمني':'نطاق العمل / ملاحظات')}{area('terms','الشروط والأحكام')}<div className="total-preview wide"><span>الإجمالي شامل الضريبة</span><strong>{money(totals(d).total,d.currency)}</strong></div><p className="form-hint wide">الضريبة حسب النسبة التي تدخلها. تُراجع الشروط وبيانات الطرفين قبل الإصدار. طباعة PDF لا تعني إرسال المستند أو توقيعه.</p></>}
</div>{error&&<p role="alert" className="form-error">{error}</p>}<div className="form-actions"><button type="submit" className={k==='document'?'secondary':'primary'} disabled={busy}><Save size={16}/>{busy?'جارٍ الحفظ…':k==='document'?'حفظ مسودة':'حفظ'}</button>{k==='document'&&<button type="button" className="primary" disabled={busy} onClick={()=>submit(true)}><FileCheck size={16}/> إصدار نسخة ثابتة</button>}<button type="button" className="secondary" disabled={busy} onClick={onClose}>إلغاء</button></div></fieldset></form></DialogContent></Dialog>}
