import {useEffect,useState} from 'react';
import {supabase} from '@/lib/supabase';
import {day,money,totals,type Row} from '@/lib/model';
import {financeSummary,type FinanceRow} from '@/lib/finance';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
const labels:Record<string,string>={income:'إيراد آخر / مستحق',expense:'مصروف',salary:'راتب',asset:'أصل للشركة'};
const blank=()=>({kind:'expense',title:'',amount:0,currency:'EGP',date:day(),due:'',status:'pending',paidDate:'',employee:'',category:'',notes:''});
export function Finance({rows,onDocument}:{rows:Row[];onDocument:(r:Row)=>void}){
 const [entries,setEntries]=useState<FinanceRow[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[month,setMonth]=useState(day().slice(0,7)),[currency,setCurrency]=useState('EGP'),[tab,setTab]=useState('all'),[editing,setEditing]=useState<FinanceRow|null|undefined>(),[d,setD]=useState(blank()),[saving,setSaving]=useState(false),[formError,setFormError]=useState('');
 async function load(){const {data,error}=await supabase!.rpc('kira_finance_list');if(error){setError(error.message)}else{setEntries(data);setError('')}setLoading(false)}
 useEffect(()=>{load();const timer=setInterval(load,30000);return()=>clearInterval(timer)},[]);
 const s=financeSummary(entries,rows,month,currency),set=(k:string,v:any)=>setD(x=>({...x,[k]:v}));
 function edit(r?:FinanceRow){setEditing(r||null);setD(r?{...r.data}:blank());setFormError('')}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setFormError('');try{const {error}=await supabase!.rpc('kira_finance_save',{payload:{id:editing?.id,version:editing?.version,data:d}});if(error)throw error;await load();setEditing(undefined)}catch(e:any){setFormError(e.message)}finally{setSaving(false)}}
 const filtered=entries.filter(r=>r.data.currency===currency&&(!month||r.data.date.startsWith(month))&&(tab==='all'||tab===r.data.kind));
 const input=(k:string,label:string,type='text',required=false)=><label className="field"><span>{label}</span><input required={required} type={type} value={(d as any)[k]} min={type==='number'?'0.01':undefined} step={type==='number'?'0.01':undefined} onChange={e=>set(k,type==='number'?Number(e.target.value):e.target.value)}/></label>;
 return <><div className="toolbar"><div className="toolbar-controls"><label>الفترة <input aria-label="شهر التقرير" type="month" value={month} onChange={e=>setMonth(e.target.value)}/></label><button className="secondary" onClick={()=>setMonth('')}>كل الفترات</button><select aria-label="عملة التقرير" value={currency} onChange={e=>setCurrency(e.target.value)}>{['EGP','SAR','USD','AED'].map(c=><option key={c}>{c}</option>)}</select><button className="secondary" onClick={load}>تحديث المالية</button></div><button className="primary" onClick={()=>edit()}>+ إضافة حركة / أصل / راتب</button></div>
 {error&&<p role="alert" className="error-banner">{error}</p>}{loading?<p>جارٍ تحميل المالية…</p>:<>
 <div className="metrics">{[['إيراد الفترة قبل ضريبة الفواتير',s.revenue],['المصروفات والمرتبات المستحقة',s.expenses],['نتيجة تشغيلية تقديرية',s.profit],['صافي حركة النقد',s.cash]].map(([label,value])=><div className="metric" key={String(label)}><span>{label}</span><strong className="money-metric">{money(Number(value),currency)}</strong></div>)}</div>
 <div className="finance-note">النتيجة التشغيلية = صافي الفواتير الصادرة + الإيرادات الأخرى − المصاريف والمرتبات، حسب تاريخ العملية. لا تشمل إهلاك الأصول أو تسويات الضرائب. صافي حركة النقد حسب تاريخ السداد ويشمل شراء الأصول؛ ليس رصيد البنك. لا تُكرر فاتورة أو دفعة عميل كإيراد يدوي.</div>
 <div className="insights-grid"><section className="panel padded"><h2>الداخل والخارج خلال الفترة</h2><div className="cash-bars">{[['نقد داخل',s.incoming],['نقد خارج',s.outgoing]].map(([label,v])=><div key={String(label)}><span>{label} · {money(Number(v),currency)}</span><div><i style={{width:`${Math.max(s.incoming,s.outgoing)?Number(v)/Math.max(s.incoming,s.outgoing)*100:0}%`}}/></div></div>)}</div></section><section className="panel padded"><h2>أرصدة كل الفترات · {currency}</h2><p>مستحق لك: <b>{money(s.receivables,currency)}</b></p><p>التزامات غير مدفوعة: <b>{money(s.payables,currency)}</b></p><p>الأصول بتكلفة الشراء: <b>{money(s.assets,currency)}</b></p></section></div>
 <div className="toolbar-controls finance-tabs">{[['all','كل الحركات'],...Object.entries(labels),['invoices','فواتير ومستحقات العملاء']].map(([k,label])=><button className={tab===k?'primary':'secondary'} key={k} onClick={()=>setTab(k)}>{label}</button>)}</div>
 <section className="panel finance-table"><table><thead><tr><th>البيان</th><th>النوع</th><th>التاريخ</th><th>المبلغ</th><th>الحالة / المتبقي</th><th>الإجراء</th></tr></thead><tbody>{tab==='invoices'?s.invoices.map(r=><tr key={r.id}><td>{r.data.title}<small>{r.data.number}</small></td><td>فاتورة</td><td>{r.data.date}</td><td>{money(totals(r.data).total,currency)}</td><td>{money(Math.max(0,totals(r.data).total-s.payments.filter(p=>p.data.documentId===r.id).reduce((n,p)=>n+p.data.amount,0)),currency)}</td><td><button className="text-button" onClick={()=>onDocument(r)}>فتح / تسجيل دفعة</button></td></tr>):filtered.map(r=><tr key={r.id}><td>{r.data.title}<small>{r.data.employee||r.data.category}</small></td><td>{labels[r.data.kind]}</td><td>{r.data.date}</td><td>{money(r.data.amount,currency)}</td><td>{r.data.status==='paid'?'مسدد':r.data.status==='void'?'ملغى':'مستحق'} {r.data.due&&<small>الاستحقاق: {r.data.due}</small>}</td><td><button className="text-button" onClick={()=>edit(r)}>تعديل</button></td></tr>)}</tbody></table>{(tab==='invoices'?!s.invoices.length:!filtered.length)&&<p className="padded muted">لا توجد سجلات لهذه الفترة والعملة. أضف أول حركة لبدء التقرير.</p>}</section>
 <p className="section-note">المرتبات تُسجَّل لكل موظف وكل شهر كحركة مستقلة قابلة للتعديل، ولا تتكرر تلقائيًا. لإلغاء حركة اختر «ملغى» فتُستبعد من الحسابات مع الاحتفاظ بها.</p></>}
 {editing!==undefined&&<Dialog open onOpenChange={v=>!v&&!saving&&setEditing(undefined)}><DialogContent className="editor" dir="rtl"><DialogHeader><DialogTitle>{editing?'تعديل الحركة':'إضافة حركة مالية'}</DialogTitle><DialogDescription>سجل المبالغ الفعلية. بيانات هذه الصفحة للمدير والحسابات فقط.</DialogDescription></DialogHeader><form onSubmit={save}><fieldset disabled={saving}><div className="form-grid"><label className="field"><span>النوع</span><select value={d.kind} onChange={e=>set('kind',e.target.value)}>{Object.entries(labels).map(([k,v])=><option value={k} key={k}>{v}</option>)}</select></label>{input('title','البيان *','text',true)}{input('amount','المبلغ *','number',true)}<label className="field"><span>العملة</span><select value={d.currency} onChange={e=>set('currency',e.target.value)}>{['EGP','SAR','USD','AED'].map(c=><option key={c}>{c}</option>)}</select></label>{input('date',d.kind==='salary'?'تاريخ استحقاق راتب الشهر *':'تاريخ العملية *','date',true)}{input('due','موعد السداد المتوقع','date')}{d.kind==='salary'?input('employee','اسم الموظف *','text',true):input('category','التصنيف / وصف الأصل')}<label className="field"><span>الحالة</span><select value={d.status} onChange={e=>set('status',e.target.value)}><option value="pending">مستحق</option><option value="paid">مسدد</option><option value="void">ملغى</option></select></label>{d.status==='paid'&&input('paidDate','تاريخ السداد الفعلي *','date',true)}<label className="field wide"><span>ملاحظات</span><textarea value={d.notes} onChange={e=>set('notes',e.target.value)}/></label></div>{formError&&<p role="alert" className="form-error">{formError}</p>}<div className="form-actions"><button className="primary" disabled={saving}>{saving?'جارٍ الحفظ…':'حفظ'}</button><button type="button" className="secondary" onClick={()=>setEditing(undefined)} disabled={saving}>إلغاء</button></div></fieldset></form></DialogContent></Dialog>}
 </>;
}
